"""lot1 moteur de fiches, echeances, alertes, notifications

Revision ID: 20784ba4f6c6
Revises: 21555a29de6a
Create Date: 2026-08-25 10:17:48.282538

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20784ba4f6c6'
down_revision: str | None = '21555a29de6a'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_definitions',
    sa.Column('name_singular', sa.String(length=80), nullable=False),
    sa.Column('name_plural', sa.String(length=80), nullable=False),
    sa.Column('icon', sa.String(length=60), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('nature', sa.Enum('asset', 'stock_item', name='record_nature'), nullable=False),
    sa.Column('title_field_key', sa.String(length=80), nullable=True),
    sa.Column('status_options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_template_key', sa.String(length=60), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_definitions_organization_id'), 'model_definitions', ['organization_id'], unique=False)
    op.create_table('alerts',
    sa.Column('source_type', sa.Enum('deadline', name='alert_source_type'), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('palier', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('emitted', 'acknowledged', 'postponed', 'resolved', name='alert_status'), nullable=False),
    sa.Column('recipient_user_id', sa.Uuid(), nullable=True),
    sa.Column('postponed_until', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'source_type', 'source_id', 'palier', name='uq_alert_source_palier')
    )
    op.create_index(op.f('ix_alerts_organization_id'), 'alerts', ['organization_id'], unique=False)
    op.create_index(op.f('ix_alerts_source_id'), 'alerts', ['source_id'], unique=False)
    op.create_table('field_definitions',
    sa.Column('model_definition_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('field_type', sa.Enum('text_short', 'text_long', 'number', 'amount', 'date', 'due_date', 'boolean', 'select', 'document', 'photo', 'phone', 'record_link', 'position', 'code', name='field_type'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('is_unique', sa.Boolean(), nullable=False),
    sa.Column('default_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('help_text', sa.String(length=300), nullable=True),
    sa.Column('show_in_list', sa.Boolean(), nullable=False),
    sa.Column('is_filterable', sa.Boolean(), nullable=False),
    sa.Column('select_options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('select_multiple', sa.Boolean(), nullable=False),
    sa.Column('number_unit', sa.String(length=20), nullable=True),
    sa.Column('visible_roles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('editable_roles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reminder_offsets_days', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reminder_repeat_days_overdue', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_definition_id'], ['model_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_field_definitions_organization_id'), 'field_definitions', ['organization_id'], unique=False)
    op.create_table('records',
    sa.Column('model_definition_id', sa.Uuid(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=60), nullable=True),
    sa.Column('site', sa.String(length=120), nullable=True),
    sa.Column('assigned_person_record_id', sa.Uuid(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_person_record_id'], ['records.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['model_definition_id'], ['model_definitions.id'], ),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_records_model_definition_id'), 'records', ['model_definition_id'], unique=False)
    op.create_index(op.f('ix_records_organization_id'), 'records', ['organization_id'], unique=False)
    op.create_table('documents',
    sa.Column('record_id', sa.Uuid(), nullable=False),
    sa.Column('field_key', sa.String(length=80), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('uploaded_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['records.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_organization_id'), 'documents', ['organization_id'], unique=False)
    op.create_table('notifications',
    sa.Column('recipient_user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=False),
    sa.Column('related_alert_id', sa.Uuid(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['related_alert_id'], ['alerts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_organization_id'), 'notifications', ['organization_id'], unique=False)
    op.create_index(op.f('ix_notifications_recipient_user_id'), 'notifications', ['recipient_user_id'], unique=False)
    op.create_table('record_events',
    sa.Column('record_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('occurred_at', sa.Date(), nullable=False),
    sa.Column('comment', sa.String(length=2000), nullable=True),
    sa.Column('cost_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('document_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['record_id'], ['records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_record_events_organization_id'), 'record_events', ['organization_id'], unique=False)
    op.create_index(op.f('ix_record_events_record_id'), 'record_events', ['record_id'], unique=False)
    op.create_table('record_deadlines',
    sa.Column('record_id', sa.Uuid(), nullable=False),
    sa.Column('field_definition_id', sa.Uuid(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['field_definition_id'], ['field_definitions.id'], ),
    sa.ForeignKeyConstraint(['record_id'], ['records.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('record_id', 'field_definition_id', name='uq_deadline_record_field')
    )
    op.create_index(op.f('ix_record_deadlines_due_date'), 'record_deadlines', ['due_date'], unique=False)
    op.create_index(op.f('ix_record_deadlines_organization_id'), 'record_deadlines', ['organization_id'], unique=False)
    # ### end Alembic commands ###

    # --- Cloisonnement multi-organisation (§14.1, §15) — même principe que le lot 0 :
    # le rôle applicatif n'est pas propriétaire de ces tables, la politique s'applique
    # donc à lui automatiquement.
    for table in (
        "model_definitions",
        "field_definitions",
        "records",
        "record_events",
        "record_deadlines",
        "documents",
        "alerts",
        "notifications",
    ):
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY org_isolation ON {table}
            USING (organization_id = current_setting('app.current_org_id', true)::uuid)
            WITH CHECK (organization_id = current_setting('app.current_org_id', true)::uuid)
            """
        )


def downgrade() -> None:
    for table in (
        "notifications",
        "alerts",
        "documents",
        "record_deadlines",
        "record_events",
        "records",
        "field_definitions",
        "model_definitions",
    ):
        op.execute(f"DROP POLICY IF EXISTS org_isolation ON {table}")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_record_deadlines_organization_id'), table_name='record_deadlines')
    op.drop_index(op.f('ix_record_deadlines_due_date'), table_name='record_deadlines')
    op.drop_table('record_deadlines')
    op.drop_index(op.f('ix_record_events_record_id'), table_name='record_events')
    op.drop_index(op.f('ix_record_events_organization_id'), table_name='record_events')
    op.drop_table('record_events')
    op.drop_index(op.f('ix_notifications_recipient_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_organization_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_documents_organization_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_records_organization_id'), table_name='records')
    op.drop_index(op.f('ix_records_model_definition_id'), table_name='records')
    op.drop_table('records')
    op.drop_index(op.f('ix_field_definitions_organization_id'), table_name='field_definitions')
    op.drop_table('field_definitions')
    op.drop_index(op.f('ix_alerts_source_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_organization_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_model_definitions_organization_id'), table_name='model_definitions')
    op.drop_table('model_definitions')
    # ### end Alembic commands ###

    # drop_table ne supprime pas les types ENUM Postgres sous-jacents (même piège
    # que org_role au lot 0) : sans ce nettoyage, un "upgrade" ultérieur échoue.
    for enum_name in ("alert_status", "alert_source_type", "field_type", "record_nature"):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
