"""lot3 recherche vues export import

Revision ID: 34315a65c7df
Revises: f23f3aa80c32
Create Date: 2026-08-25 11:08:41.743214

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '34315a65c7df'
down_revision: str | None = 'f23f3aa80c32'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_views',
    sa.Column('model_definition_id', sa.Uuid(), nullable=False),
    sa.Column('owner_user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('columns', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sort_key', sa.String(length=80), nullable=True),
    sa.Column('sort_direction', sa.String(length=4), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_definition_id'], ['model_definitions.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_views_model_definition_id'), 'saved_views', ['model_definition_id'], unique=False)
    op.create_index(op.f('ix_saved_views_organization_id'), 'saved_views', ['organization_id'], unique=False)
    op.create_index(op.f('ix_saved_views_owner_user_id'), 'saved_views', ['owner_user_id'], unique=False)
    # ### end Alembic commands ###

    # Cloisonnement multi-organisation (§14.1, §15). Pas de cas de bootstrap ici
    # (contrairement à memberships) : ces routes passent toujours par
    # get_org_context, le contexte est donc déjà établi à la première requête.
    op.execute("ALTER TABLE saved_views ENABLE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY org_isolation ON saved_views
        USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
        WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
        """
    )


def downgrade() -> None:
    op.execute("DROP POLICY IF EXISTS org_isolation ON saved_views")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_views_owner_user_id'), table_name='saved_views')
    op.drop_index(op.f('ix_saved_views_organization_id'), table_name='saved_views')
    op.drop_index(op.f('ix_saved_views_model_definition_id'), table_name='saved_views')
    op.drop_table('saved_views')
    # ### end Alembic commands ###
