"""lot5 fondations hors-ligne: fusion champ par champ, conflits, uploads reprenables

Revision ID: 73d1437e41a1
Revises: 1a5a32610501
Create Date: 2026-08-25 16:02:55.660215

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '73d1437e41a1'
down_revision: str | None = '1a5a32610501'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('record_field_conflicts',
    sa.Column('record_id', sa.Uuid(), nullable=False),
    sa.Column('field_key', sa.String(length=80), nullable=False),
    sa.Column('kept_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('kept_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rejected_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rejected_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['records.id'], ),
    sa.ForeignKeyConstraint(['rejected_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_record_field_conflicts_organization_id'), 'record_field_conflicts', ['organization_id'], unique=False)
    op.create_index(op.f('ix_record_field_conflicts_record_id'), 'record_field_conflicts', ['record_id'], unique=False)

    # Cloisonnement multi-organisation (§14.1, §15) — ces routes passent toujours
    # par get_org_context (admin uniquement, voir sync.py), le contexte est déjà établi.
    op.execute("ALTER TABLE record_field_conflicts ENABLE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY org_isolation ON record_field_conflicts
        USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
        WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
        """
    )

    op.create_table('upload_sessions',
    sa.Column('record_id', sa.Uuid(), nullable=False),
    sa.Column('field_key', sa.String(length=80), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('total_bytes', sa.BigInteger(), nullable=False),
    sa.Column('chunk_size', sa.Integer(), nullable=False),
    sa.Column('chunks_received', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['record_id'], ['records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upload_sessions_organization_id'), 'upload_sessions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_upload_sessions_record_id'), 'upload_sessions', ['record_id'], unique=False)

    op.execute("ALTER TABLE upload_sessions ENABLE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY org_isolation ON upload_sessions
        USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
        WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
        """
    )

    op.add_column('audit_logs', sa.Column('client_operation_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_audit_logs_client_operation_id'), 'audit_logs', ['client_operation_id'], unique=False)
    # server_default seulement pour le backfill des lignes existantes — la classe
    # ORM garde default=dict (Python), la colonne n'a pas besoin de le conserver.
    op.add_column(
        'records',
        sa.Column(
            'field_updated_at', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'{}'::jsonb")
        ),
    )
    op.alter_column('records', 'field_updated_at', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('records', 'field_updated_at')
    op.drop_index(op.f('ix_audit_logs_client_operation_id'), table_name='audit_logs')
    op.drop_column('audit_logs', 'client_operation_id')

    op.execute("DROP POLICY IF EXISTS org_isolation ON upload_sessions")
    op.drop_index(op.f('ix_upload_sessions_record_id'), table_name='upload_sessions')
    op.drop_index(op.f('ix_upload_sessions_organization_id'), table_name='upload_sessions')
    op.drop_table('upload_sessions')

    op.execute("DROP POLICY IF EXISTS org_isolation ON record_field_conflicts")
    op.drop_index(op.f('ix_record_field_conflicts_record_id'), table_name='record_field_conflicts')
    op.drop_index(op.f('ix_record_field_conflicts_organization_id'), table_name='record_field_conflicts')
    op.drop_table('record_field_conflicts')
    # ### end Alembic commands ###
