"""lot4 abonnements et espace editeur

Revision ID: 8d25168dad39
Revises: 34315a65c7df
Create Date: 2026-08-25 11:31:20.595161

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8d25168dad39'
down_revision: str | None = '34315a65c7df'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currencies',
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('display_format', sa.String(length=40), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('offers',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('duration_months', sa.Integer(), nullable=False),
    sa.Column('storage_quota_gb', sa.Integer(), nullable=False),
    sa.Column('user_quota', sa.Integer(), nullable=True),
    sa.Column('prices', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('offer_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('declared', 'validated', 'rejected', name='payment_status'), nullable=False),
    sa.Column('declared_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('declared_reference', sa.String(length=120), nullable=True),
    sa.Column('declared_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('validated_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=True),
    sa.Column('method', sa.Enum('mobile_money', 'bank_transfer', 'cash', 'other', name='payment_method'), nullable=True),
    sa.Column('validated_reference', sa.String(length=120), nullable=True),
    sa.Column('validated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.String(length=300), nullable=True),
    sa.Column('extension_reason', sa.String(length=300), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['declared_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.ForeignKeyConstraint(['validated_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_organization_id'), 'payments', ['organization_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('offer_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('trial', 'active', 'read_only', 'suspended', 'archived', name='subscription_status'), nullable=False),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read_only_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('suspended_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', name='uq_subscription_organization')
    )
    op.create_index(op.f('ix_subscriptions_organization_id'), 'subscriptions', ['organization_id'], unique=False)
    op.create_table('invoices',
    sa.Column('payment_id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_index(op.f('ix_invoices_organization_id'), 'invoices', ['organization_id'], unique=False)
    # ### end Alembic commands ###

    # --- Cloisonnement (§14.1, §15) avec une exception délibérée : subscriptions,
    # payments et invoices sont les seules tables où l'éditeur voit à travers
    # toutes les organisations (§13 — offres, file des règlements, liste des
    # organisations). Ailleurs (fiches, stock, documents...), aucune politique de
    # ce type n'existe : l'éditeur y reste sans accès par défaut (§4.3), ce
    # contournement est donc strictement limité à ces trois tables de facturation.
    for table in ("subscriptions", "payments", "invoices"):
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY org_isolation ON {table}
            USING (
                organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid
                OR NULLIF(current_setting('app.is_platform_admin', true), '') = 'true'
            )
            WITH CHECK (
                organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid
                OR NULLIF(current_setting('app.is_platform_admin', true), '') = 'true'
            )
            """
        )

    # `offers` et `currencies` ne sont pas cloisonnées par organisation : c'est un
    # catalogue partagé (§13), lu par toutes les organisations. Rien à activer ici.

    # L'éditeur doit aussi pouvoir compter les membres actifs de n'importe quelle
    # organisation pour la liste "mes organisations" côté éditeur (§13 : "nombre
    # d'utilisateurs") — un simple dénombrement, pas un accès aux fiches. On étend
    # la politique de lecture de `memberships` posée au lot 1 plutôt que d'en
    # ajouter une seconde qui se chevaucherait.
    op.execute("DROP POLICY IF EXISTS select_own_or_org ON memberships")
    op.execute(
        """
        CREATE POLICY select_own_or_org ON memberships FOR SELECT
        USING (
            organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid
            OR user_id = NULLIF(current_setting('app.current_user_id', true), '')::uuid
            OR NULLIF(current_setting('app.is_platform_admin', true), '') = 'true'
        )
        """
    )

    # Numérotation de facture (§12.4) : une séquence Postgres plutôt qu'un
    # COUNT(*) applicatif, qui serait sujet à une course entre deux validations
    # de paiement concurrentes.
    op.execute("CREATE SEQUENCE IF NOT EXISTS invoice_number_seq START 1")


def downgrade() -> None:
    op.execute("DROP SEQUENCE IF EXISTS invoice_number_seq")

    op.execute("DROP POLICY IF EXISTS select_own_or_org ON memberships")
    op.execute(
        """
        CREATE POLICY select_own_or_org ON memberships FOR SELECT
        USING (
            organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid
            OR user_id = NULLIF(current_setting('app.current_user_id', true), '')::uuid
        )
        """
    )

    for table in ("invoices", "payments", "subscriptions"):
        op.execute(f"DROP POLICY IF EXISTS org_isolation ON {table}")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoices_organization_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_subscriptions_organization_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_payments_organization_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_table('offers')
    op.drop_table('currencies')
    # ### end Alembic commands ###

    # drop_table ne supprime pas les types ENUM Postgres sous-jacents (même piège
    # que les lots précédents) : sans ce nettoyage, un "upgrade" ultérieur échoue.
    for enum_name in ("payment_method", "payment_status", "subscription_status"):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
