"""client operation ids pour idempotence hors-ligne

Revision ID: b83491b7a801
Revises: 8d25168dad39
Create Date: 2026-08-25 11:44:56.615436

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b83491b7a801'
down_revision: str | None = '8d25168dad39'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_movements', sa.Column('client_operation_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_stock_movements_client_operation_id'), 'stock_movements', ['client_operation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_movements_client_operation_id'), table_name='stock_movements')
    op.drop_column('stock_movements', 'client_operation_id')
    # ### end Alembic commands ###
