"""lot2 module stock

Revision ID: f23f3aa80c32
Revises: 5799f8fae891
Create Date: 2026-08-25 10:54:12.851386

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f23f3aa80c32'
down_revision: str | None = '5799f8fae891'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('depots',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_depots_organization_id'), 'depots', ['organization_id'], unique=False)
    op.create_table('article_configs',
    sa.Column('record_id', sa.Uuid(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('purchase_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('sale_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('variant_attribute_labels', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('lot_tracking_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_consigned', sa.Boolean(), nullable=False),
    sa.Column('deposit_unit_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['records.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('record_id')
    )
    op.create_index(op.f('ix_article_configs_organization_id'), 'article_configs', ['organization_id'], unique=False)
    op.create_table('article_variants',
    sa.Column('record_id', sa.Uuid(), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('default_threshold', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_variants_organization_id'), 'article_variants', ['organization_id'], unique=False)
    op.create_index(op.f('ix_article_variants_record_id'), 'article_variants', ['record_id'], unique=False)
    op.create_table('consignment_levels',
    sa.Column('variant_id', sa.Uuid(), nullable=False),
    sa.Column('depot_id', sa.Uuid(), nullable=False),
    sa.Column('empty_count', sa.Integer(), nullable=False),
    sa.Column('in_circulation_count', sa.Integer(), nullable=False),
    sa.Column('deposit_amount_collected', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['depot_id'], ['depots.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['article_variants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('variant_id', 'depot_id', name='uq_consignment_level')
    )
    op.create_index(op.f('ix_consignment_levels_organization_id'), 'consignment_levels', ['organization_id'], unique=False)
    op.create_table('depot_thresholds',
    sa.Column('variant_id', sa.Uuid(), nullable=False),
    sa.Column('depot_id', sa.Uuid(), nullable=False),
    sa.Column('threshold', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['depot_id'], ['depots.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['article_variants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('variant_id', 'depot_id', name='uq_depot_threshold')
    )
    op.create_index(op.f('ix_depot_thresholds_organization_id'), 'depot_thresholds', ['organization_id'], unique=False)
    op.create_table('stock_levels',
    sa.Column('variant_id', sa.Uuid(), nullable=False),
    sa.Column('depot_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['depot_id'], ['depots.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['article_variants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('variant_id', 'depot_id', name='uq_stock_level')
    )
    op.create_index(op.f('ix_stock_levels_organization_id'), 'stock_levels', ['organization_id'], unique=False)
    op.create_table('stock_lots',
    sa.Column('variant_id', sa.Uuid(), nullable=False),
    sa.Column('depot_id', sa.Uuid(), nullable=False),
    sa.Column('lot_number', sa.String(length=60), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('remaining_quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['depot_id'], ['depots.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['article_variants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('variant_id', 'depot_id', 'lot_number', name='uq_stock_lot')
    )
    op.create_index(op.f('ix_stock_lots_expiry_date'), 'stock_lots', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_stock_lots_organization_id'), 'stock_lots', ['organization_id'], unique=False)
    op.create_table('stock_movements',
    sa.Column('variant_id', sa.Uuid(), nullable=False),
    sa.Column('depot_id', sa.Uuid(), nullable=False),
    sa.Column('movement_type', sa.Enum('entry', 'exit', 'transfer_out', 'transfer_in', 'adjustment', name='movement_type'), nullable=False),
    sa.Column('quantity_delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=60), nullable=True),
    sa.Column('supplier', sa.String(length=120), nullable=True),
    sa.Column('beneficiary', sa.String(length=120), nullable=True),
    sa.Column('cost_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('lot_number', sa.String(length=60), nullable=True),
    sa.Column('lot_expiry_date', sa.Date(), nullable=True),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('transfer_group_id', sa.Uuid(), nullable=True),
    sa.Column('adjustment_counted_quantity', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['depot_id'], ['depots.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['article_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_movements_depot_id'), 'stock_movements', ['depot_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_organization_id'), 'stock_movements', ['organization_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_transfer_group_id'), 'stock_movements', ['transfer_group_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_variant_id'), 'stock_movements', ['variant_id'], unique=False)
    # ### end Alembic commands ###

    # Le type ENUM alert_source_type existe depuis le lot 1 avec la seule valeur
    # "deadline" ; le lot 2 introduit deux nouvelles sources d'alerte (§8.1). Sans
    # ajout, tout INSERT avec ces valeurs échoue au runtime (jamais au moment des
    # migrations elles-mêmes, donc jamais repéré par un simple `alembic upgrade`).
    op.execute("ALTER TYPE alert_source_type ADD VALUE IF NOT EXISTS 'stock_threshold'")
    op.execute("ALTER TYPE alert_source_type ADD VALUE IF NOT EXISTS 'lot_expiry'")

    # --- Cloisonnement multi-organisation (§14.1, §15) — même principe que les lots
    # précédents : le rôle applicatif n'est pas propriétaire de ces tables.
    for table in (
        "depots",
        "article_configs",
        "article_variants",
        "consignment_levels",
        "depot_thresholds",
        "stock_levels",
        "stock_lots",
        "stock_movements",
    ):
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY org_isolation ON {table}
            USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
            WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)
            """
        )

    # --- Mouvements immuables (§7.3, §11.3, §11.4) : jamais modifiés ni supprimés,
    # on corrige par un mouvement inverse — même mécanique que audit_logs (lot 0).
    op.execute(
        """
        CREATE TRIGGER stock_movements_no_update
        BEFORE UPDATE ON stock_movements
        FOR EACH ROW EXECUTE FUNCTION prevent_audit_log_mutation()
        """
    )
    op.execute(
        """
        CREATE TRIGGER stock_movements_no_delete
        BEFORE DELETE ON stock_movements
        FOR EACH ROW EXECUTE FUNCTION prevent_audit_log_mutation()
        """
    )

    # --- StockLevel tenu à jour par trigger, pas par le code applicatif : deux
    # mouvements concurrents sur le même (variante, dépôt) s'additionnent toujours
    # atomiquement, jamais un conflit d'écriture (§11.3, §11.4 — condition posée
    # dès le lot 0 pour que le lot 5 hors-ligne n'ait jamais à réécrire ce socle).
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    op.execute(
        """
        CREATE OR REPLACE FUNCTION apply_stock_movement() RETURNS trigger AS $$
        BEGIN
            INSERT INTO stock_levels (id, organization_id, variant_id, depot_id, quantity, updated_at)
            VALUES (gen_random_uuid(), NEW.organization_id, NEW.variant_id, NEW.depot_id, NEW.quantity_delta, now())
            ON CONFLICT (variant_id, depot_id)
            DO UPDATE SET quantity = stock_levels.quantity + EXCLUDED.quantity, updated_at = now();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql
        """
    )
    op.execute(
        """
        CREATE TRIGGER stock_movements_apply
        AFTER INSERT ON stock_movements
        FOR EACH ROW EXECUTE FUNCTION apply_stock_movement()
        """
    )


def downgrade() -> None:
    # Postgres ne permet pas de retirer une valeur d'un type ENUM : "stock_threshold"
    # et "lot_expiry" restent déclarées mais inutilisées après ce downgrade — sans
    # conséquence, aucune ligne ne peut plus les référencer une fois ce lot défait.
    op.execute("DROP TRIGGER IF EXISTS stock_movements_apply ON stock_movements")
    op.execute("DROP FUNCTION IF EXISTS apply_stock_movement()")
    op.execute("DROP TRIGGER IF EXISTS stock_movements_no_delete ON stock_movements")
    op.execute("DROP TRIGGER IF EXISTS stock_movements_no_update ON stock_movements")

    for table in (
        "stock_movements",
        "stock_lots",
        "stock_levels",
        "depot_thresholds",
        "consignment_levels",
        "article_variants",
        "article_configs",
        "depots",
    ):
        op.execute(f"DROP POLICY IF EXISTS org_isolation ON {table}")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_movements_variant_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_transfer_group_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_organization_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_depot_id'), table_name='stock_movements')
    op.drop_table('stock_movements')
    op.drop_index(op.f('ix_stock_lots_organization_id'), table_name='stock_lots')
    op.drop_index(op.f('ix_stock_lots_expiry_date'), table_name='stock_lots')
    op.drop_table('stock_lots')
    op.drop_index(op.f('ix_stock_levels_organization_id'), table_name='stock_levels')
    op.drop_table('stock_levels')
    op.drop_index(op.f('ix_depot_thresholds_organization_id'), table_name='depot_thresholds')
    op.drop_table('depot_thresholds')
    op.drop_index(op.f('ix_consignment_levels_organization_id'), table_name='consignment_levels')
    op.drop_table('consignment_levels')
    op.drop_index(op.f('ix_article_variants_record_id'), table_name='article_variants')
    op.drop_index(op.f('ix_article_variants_organization_id'), table_name='article_variants')
    op.drop_table('article_variants')
    op.drop_index(op.f('ix_article_configs_organization_id'), table_name='article_configs')
    op.drop_table('article_configs')
    op.drop_index(op.f('ix_depots_organization_id'), table_name='depots')
    op.drop_table('depots')
    # ### end Alembic commands ###

    # drop_table ne supprime pas le type ENUM Postgres sous-jacent (même piège
    # que les lots précédents) : sans ce nettoyage, un "upgrade" ultérieur échoue.
    sa.Enum(name="movement_type").drop(op.get_bind(), checkfirst=True)
