import {
  Archive,
  Baby,
  Badge,
  Battery,
  Boxes,
  Briefcase,
  Bus,
  Camera,
  Car,
  ClipboardList,
  Cog,
  Container,
  CreditCard,
  Droplet,
  FileText,
  FireExtinguisher,
  Flame,
  Fuel,
  Gauge,
  GraduationCap,
  Hammer,
  HardHat,
  House,
  IdCard,
  Landmark,
  Layers,
  Package,
  Phone,
  PlaneTakeoff,
  Printer,
  QrCode,
  Refrigerator,
  Shapes,
  Shield,
  ShieldCheck,
  Ship,
  Shirt,
  Snowflake,
  Syringe,
  Tag,
  Tent,
  Truck,
  User,
  Users,
  UtensilsCrossed,
  Warehouse,
  Wrench,
  type LucideIcon,
} from "lucide-react";

/**
 * Registre d'icônes pour les modèles de fiche. Les clés correspondent exactement
 * aux valeurs semées par le backend (`backend/app/seeds/templates.py:icon`, ex.
 * "car", "user", "flame", "file-text", "shirt") ainsi qu'au jeu proposé par le
 * sélecteur d'icônes du constructeur de modèles — mêmes clés des deux côtés.
 *
 * `getModelIcon` retombe honnêtement sur une icône générique (`Shapes`) si la
 * valeur stockée ne correspond à rien ici, plutôt que de planter le rendu.
 */
export const MODEL_ICONS: Record<string, LucideIcon> = {
  car: Car,
  bus: Bus,
  truck: Truck,
  "plane-takeoff": PlaneTakeoff,
  ship: Ship,
  fuel: Fuel,
  user: User,
  users: Users,
  "id-card": IdCard,
  "graduation-cap": GraduationCap,
  baby: Baby,
  "briefcase": Briefcase,
  "hard-hat": HardHat,
  flame: Flame,
  "fire-extinguisher": FireExtinguisher,
  shield: Shield,
  "shield-check": ShieldCheck,
  "file-text": FileText,
  "clipboard-list": ClipboardList,
  "credit-card": CreditCard,
  landmark: Landmark,
  shirt: Shirt,
  tag: Tag,
  package: Package,
  boxes: Boxes,
  container: Container,
  warehouse: Warehouse,
  archive: Archive,
  layers: Layers,
  droplet: Droplet,
  snowflake: Snowflake,
  refrigerator: Refrigerator,
  battery: Battery,
  wrench: Wrench,
  hammer: Hammer,
  cog: Cog,
  gauge: Gauge,
  syringe: Syringe,
  camera: Camera,
  phone: Phone,
  "qr-code": QrCode,
  printer: Printer,
  house: House,
  tent: Tent,
  "utensils-crossed": UtensilsCrossed,
  badge: Badge,
};

/** Clés proposées par le sélecteur d'icônes, dans un ordre pensé pour couvrir les
 * cas d'usage les plus courants (véhicules, personnel, sécurité, stock) en premier. */
export const MODEL_ICON_PICKER_KEYS: string[] = [
  "car",
  "truck",
  "bus",
  "ship",
  "plane-takeoff",
  "fuel",
  "user",
  "users",
  "id-card",
  "graduation-cap",
  "briefcase",
  "hard-hat",
  "flame",
  "fire-extinguisher",
  "shield",
  "shield-check",
  "file-text",
  "clipboard-list",
  "credit-card",
  "landmark",
  "shirt",
  "tag",
  "package",
  "boxes",
  "container",
  "warehouse",
  "archive",
  "layers",
  "droplet",
  "snowflake",
  "refrigerator",
  "battery",
  "wrench",
  "hammer",
  "cog",
  "gauge",
  "syringe",
  "camera",
  "phone",
  "qr-code",
  "printer",
  "house",
  "tent",
  "utensils-crossed",
];

export function getModelIcon(iconKey: string | null | undefined): LucideIcon {
  if (!iconKey) return Shapes;
  return MODEL_ICONS[iconKey] ?? Shapes;
}
